### PR TITLE
Update README.md 🦅🦅🦅🦅🦅🦅🦅🦅 

### PR DESCRIPTION
**Pull request by Dawsson**
Americanize the readme
image

### CODE REVIEW

**Comment by SimplyMerlin** [comment]
LGTM!

**Comment by UwUAroze** [comment]
nO. DOES NOT LOOK GOOD TO YOU.

**Review by DebitCardz — APPROVED** [review]
LGTM! SHIP IT!!

**Comment by UwUAroze** [comment]
shipped.

**Pull request closed without merging**
